### ISSUE TITLE
Event erstellen

### ISSUE THREAD

**Issue by kraemer64** [iubh-projekt-software-engineering/tierfreund.#18]
sqlalchemy.exc.InvalidRequestError: Entity '<class 'app.event.model.Event'>' has no property 'user_id'

Diese Meldung erscheint beim Versuch einen neuen Termin zu erstellen.

**Comment by kraemer64** [comment]
Gefixed

**Comment by janmarkuslanger** [comment]
Wegen Time und dem Titel des issues ist das immer noch offen

**Comment by janmarkuslanger** [comment]
@kraemer64 ein event erstellen läuft nun wie erwartet
