### ISSUE TITLE
Event details aufruf

### ISSUE THREAD

**Issue by kraemer64** [iubh-projekt-software-engineering/tierfreund.#19]
Beim Versuch die Details der angelegten Events zu öffen, erscheint dieser Fehler:

sqlalchemy.exc.InvalidRequestError: Entity '<class 'app.event.model.Event'>' has no property 'user_id'

**Comment by janmarkuslanger** [comment]
@kraemer64 prüf bitte nochmal deinen entwicklungsstand. Die klasse hat das attribut das habe ich schon erweitert.

**Comment by janmarkuslanger** [comment]
@kraemer64 das ist wieder der gleiche fehler wie bei der index. schau dir mal den query an. Wie du abfragst. Wenn du hlfe brauchst geb bescheid

**Comment by janmarkuslanger** [comment]
@kraemer64 ich fixe das eben dann geht es schneller.
