### ISSUE TITLE
Events demodaten erstellen 

### ISSUE THREAD

**Issue by janmarkuslanger** [iubh-projekt-software-engineering/tierfreund.#22]

**Comment by janmarkuslanger** [comment]
@kraemer64 kannst du das noch machen?

**Comment by janmarkuslanger** [comment]
@kraemer64 soll ich das auch machen?

**Comment by kraemer64** [comment]
@janmarkuslanger Ja bitte, ich raff es nicht. Auf die schnelle verstehe ich das mit den relationalen ORM mapping nicht...

**Comment by janmarkuslanger** [comment]
@kraemer64 ok
