### ISSUE TITLE
Fehlerhaftes Listing styling 

### ISSUE THREAD

**Issue by janmarkuslanger** [iubh-projekt-software-engineering/tierfreund.#33]
<img width="1336" alt="Bildschirmfoto 2020-07-18 um 22 17 36" src="https://user-images.githubusercontent.com/26633123/87861230-97cd6180-c944-11ea-8b6c-29b1b621f50d.png">

**Comment by kraemer64** [comment]
@janmarkuslanger Listing styling ist angepasst.
