### ISSUE TITLE
Form required prüfen

### ISSUE THREAD

**Issue by janmarkuslanger** [iubh-projekt-software-engineering/tierfreund.#34]
@kraemer64 du müsstest nun bei allen form macros die möglichkeit haben diese n den parameter required=BOOL zu übergeben. Bitte in abhängih von den models immer prüfen ob ein html feld required haben sollte.

**Comment by kraemer64** [comment]
@janmarkuslanger Alle html Felder besitzen jetzt required in Abhängigkeit der Models.
