### ISSUE TITLE
Bild bei Termine Details verschoben

### ISSUE THREAD

**Issue by kraemer64** [iubh-projekt-software-engineering/tierfreund.#36]

**Comment by janmarkuslanger** [comment]
@kraemer64 die komplette stage fehlt ja bzw wird fehlerhaft dargestellt

**Comment by janmarkuslanger** [comment]
@kraemer64 schließe das erstmal. es gibt auf der detailseite leider noch weitere fehler. farbe ist wieder fix reingeschrieben. gehe da jetzt ran.
