### ISSUE TITLE
Formular für Tieranlage - 'Gewicht eingeben' statt 0

### ISSUE THREAD

**Issue by renerausch** [iubh-projekt-software-engineering/tierfreund.#53]
Im Formular der Tieranlage ist eine 0 ohne Beschreibung. Hier sollte 'Gewicht eingeben' vorbelegt sein, damit der User weiß, was er Eintragen muss.

**Comment by kraemer64** [comment]
https://github.com/iubh-projekt-software-engineering/tierfreund./pull/51

Dieser PR passt es an.
