### ISSUE TITLE
Text fehlt auf Zweiter Onboarding-Seite am iPhone

### ISSUE THREAD

**Issue by renerausch** [iubh-projekt-software-engineering/tierfreund.#54]
![image](https://user-images.githubusercontent.com/65887006/87979629-a47fc000-cad2-11ea-80b9-6ab16d8943a2.png)

Siehe Screenshot

**Comment by janmarkuslanger** [comment]
@kraemer64 bitte auf den Seiten für SMALL <-! die font sizes reduzieren auf large soll es so bleiben
