### ISSUE TITLE
Geburtsdatum des Tieres im Formular am iPhone nur als Strich

### ISSUE THREAD

**Issue by renerausch** [iubh-projekt-software-engineering/tierfreund.#56]
![image](https://user-images.githubusercontent.com/65887006/87980071-4c958900-cad3-11ea-8a8c-b76d09de9458.png)

**Comment by janmarkuslanger** [comment]
@renerausch das wird das gleiche Spiel sein, weil du safari nutzt. Ist ja wie schon besprochen dann erstmal nicht supportet
