### ISSUE TITLE
Löschen von Erinnerungen nicht möglich

### ISSUE THREAD

**Issue by renerausch** [iubh-projekt-software-engineering/tierfreund.#59]
![image](https://user-images.githubusercontent.com/65887006/87980327-b877f180-cad3-11ea-8589-0b26a2d53879.png)

**Comment by kraemer64** [comment]
@janmarkuslanger Hier bin ich gerade dran. Den internal server error konnte ich fixen. Aber das event wird noch nicht gelöscht.
In der Konsole erhalte ich folgenden Fehler:

Class 'sqlalchemy.util._collections.result' is not mapped

Hier geht es wohl um die Event Klasse.

**Comment by kraemer64** [comment]
@janmarkuslanger Ok habe es gefixed. Das Problem lag daran, dass dem session.delete() eine result list übergeben worden ist. Ich erstelle PR.
