### ISSUE TITLE
NoReferencedTableError

### ISSUE THREAD

**Issue by kraemer64** [iubh-projekt-software-engineering/tierfreund.#7]
Beim ausführen von: 
-del app.db
-python db_setup.py

Erscheint folgender Fehler:
sqlalchemy.exc.NoReferencedTableError: Foreign key associated with column 'events.doc_id' 
could not find table 'doc' with which to generate a foreign key to target column 'id'

Liegt das am Konflikt?
- In Datei event/model.py 
doc_id = db.Column(db.Integer, db.ForeignKey('doc.id')) ===> doc_id = db.Column(db.Integer, db.ForeignKey('docs.id'))

**Comment by janmarkuslanger** [comment]
@kraemer64 du hast in der model datei ein `=` das hatte ich aber schon gefixxt und in die master grpackt
